/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Conceptos.*;
import Frame_Velocidad.*;
import Frames_Vectores.*;
import Frames_Movimiento.*;
import Conversion.*;
import Doppler.*;
import Frames_fuerzas_aceleracion.*;

import javax.swing.JOptionPane;

/**
 *
 * @author Microsoft
 */
public class Reseñas extends javax.swing.JFrame {

    /**
     * Creates new form Reseñas
     */
    public Reseñas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("BIENVENIDO!!..");

        btn1.setText("CALCULADORA DE MOVIMIENTOS");
        btn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        jButton2.setText("VELOCIDAD ANGULAR");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("FUERZAS Y ACELERACIONES");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("OPERACIONES CON VECTORES");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("SELECCIONA UN TEMA A REALIZAR...");

        jButton1.setText("CALCULADORA DE NOTACION CIENTIFICA");
        jButton1.setAutoscrolls(true);
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("CALCULADORA EFECTO DOPPLER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed

        CaidaLibre obj = new CaidaLibre();
        Concepto_MRU obj1 = new Concepto_MRU();
        Concepto_MRUV obj2 = new Concepto_MRUV();
        Concepto_Parabola obj3 = new Concepto_Parabola();
        Concepto_Pendulo obj4 = new Concepto_Pendulo();

        int dato = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero para ir a la ventana \n"
                + "1. Si quiere calcular el MRU" + "\n"
                + "2. Si quiere calcular el MRUV" + "\n"
                + "3. Si quiere calcular la PARABOLA" + "\n"
                + "4. Si quiere calcular el PENDULO" + "\n"
                + "5. Si quiere calcular la CAIDA LIBRE"));

        switch (dato) {
            case 1:
                obj1.setVisible(true);
                break;
            case 2:
                obj2.setVisible(true);
                break;
            case 3:
                obj3.setVisible(true);
                break;
            case 4:
                obj4.setVisible(true);
                break;
            case 5:
                obj.setVisible(true);
                break;
        }
        hide();


    }//GEN-LAST:event_btn1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        Suma_vectores obj = new Suma_vectores();
        Resta_Vectores obj1 = new Resta_Vectores();
        Producto_escalar_1 obj2 = new Producto_escalar_1();
        Producto_escalar_2 obj3 = new Producto_escalar_2();
        Producto_escalar_3 obj4 = new Producto_escalar_3();
        Producto_Vectorial obj5 = new Producto_Vectorial();

        int dato = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero para ir a la ventana \n"
                + "1. Si quieres sumar vectores" + "\n"
                + "2. Si quieres restar vectores" + "\n"
                + "3. Si quieres realizar Producto escalar " + "\n"
                + "4. Si quieres realizar producto vectorial"));

        switch (dato) {
            case 1:
                obj.setVisible(true);
                hide();
                break;
            case 2:
                obj1.setVisible(true);
                hide();
                break;
            case 3:
                int dato1 = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero para continuar\n"
                        + "1. Si la dimension es de 2" + "\n"
                        + "2. Si la dimension es de 3" + "\n"
                        + "3. Si tienes los modulos y el angulo"));
                switch (dato1) {
                    case 1:
                        obj2.setVisible(true);
                        break;
                    case 2:
                        obj3.setVisible(true);
                        break;
                    default:
                        obj4.setVisible(true);
                        break;
                }
                break;
            case 4:
                obj5.setVisible(true);
                hide();
                break;

        }
        hide();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Rads_hz rh = new Rads_hz();
        Rads_rpm rp = new Rads_rpm();
        Rpm_hz rphz = new Rpm_hz();
        Velocidad_Angular1 va1 = new Velocidad_Angular1();
        Velocidad_Angular2 va2 = new Velocidad_Angular2();
        Velocidad_Angular3 va3 = new Velocidad_Angular3();

        int dato = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero para ir a la ventana \n"
                + "1. Si quieres convertir Rad/s a Hz" + "\n"
                + "2. Si quieres convertir Rad/s a RPM" + "\n"
                + "3. Si quieres convertir RPM a Hz " + "\n"
                + "4. Si quieres calcular la Velocidad Angular"));

        switch (dato) {
            case 1:
                rh.setVisible(true);
                break;
            case 2:
                rp.setVisible(true);
                break;
            case 3:
                rphz.setVisible(true);
                break;
            case 4:
                int dato1 = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero para continuar\n"
                        + "1. Si tiene Angulo e Intervalo de Tiempo" + "\n"
                        + "2. Si solo tiene la frecuencia" + "\n"
                        + "3. Si conoces la Velocidad Lineal y el Radio "));
                switch (dato1) {
                    case 1:
                        va1.setVisible(true);
                        break;
                    case 2:
                        va2.setVisible(true);
                        break;
                    default:
                        va3.setVisible(true);
                        break;
                }
                break;
        }
        hide();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Aceleracion1 a1 = new Aceleracion1();
        Aceleracion2 a2 = new Aceleracion2();
        Aceleracion3 a3 = new Aceleracion3();
        Ley_newton a4 = new Ley_newton();
        NoFriccion1 a5 = new NoFriccion1();
        NoFriccion2 a6 = new NoFriccion2();
        NoFriccion3 a7 = new NoFriccion3();
        NoFriccion4 a8 = new NoFriccion4();
        Frame_friccion1 fr1 = new Frame_friccion1();
        Frame_friccion2 fr2 = new Frame_friccion2();
        Centripeta1 c1 = new Centripeta1();
        Centripeta2 c2 = new Centripeta2();

        int dato = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero para ir a la ventana \n"
                + "1. Si quieres hallar la aceleracion" + "\n"
                + "2. Si quieres calcular la Segunda Ley de Newton" + "\n"
                + "3. Si quieres calcular la aceleración en un plano inclinado" + "\n"
                + "4. Si quieres calcular la fuerza de friccion" + "\n"
                + "5. Si quieres calcular la fuerza centripeta"));

        switch (dato) {
            case 1:
                int dato1 = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero para continuar\n"
                        + "1. Si conoces las velocidades y el Tiempo" + "\n"
                        + "2. Si tienes las Posiciones (final e inicial), Velocidad Inicial y el Tiempo" + "\n"
                        + "3. Si concoces velocidades y posiciones en dos instantes: "));
                switch (dato1) {
                    case 1:
                        a1.setVisible(true);
                        break;
                    case 2:
                        a2.setVisible(true);
                        break;
                    default:
                        a3.setVisible(true);
                        break;
                }
                break;
            case 2:
                a4.setVisible(true);
                break;
            case 3:
                int dato2 = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero para continuar\n"
                        + "1. Si el plano es inclinado sin friccion" + "\n"
                        + "2. Si el plano es inclinado con friccion"));
                switch (dato2) {
                    case 1:
                        int dato3 = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero para continuar\n"
                                + "1. Si tienes solo el angulo" + "\n"
                                + "2. Si tienes el angulo[θ] y altura[h]"));
                        switch (dato3) {
                            case 1:
                                a5.setVisible(true);
                                break;
                            default:
                                a6.setVisible(true);
                                break;
                        }
                        break;
                    default:
                        int dato4 = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero para continuar\n"
                                + "1. Si tienes el angulo y el coeficiente de fricción[μ]" + "\n"
                                + "2. Si tienes altura[h], coeficiente[μ], angulo[θ]"));
                        switch (dato4) {
                            case 1:
                                a7.setVisible(true);
                                break;
                            default:
                                a8.setVisible(true);
                                break;
                        }

                        break;

                }
                break;
            case 4:
                int dato5 = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero para continuar\n"
                        + "1. Si la fuerza es Normal[N]" + "\n"
                        + "2. Si la fuerza depende del peso[Kg]"));
                switch (dato5) {
                    case 1:
                        fr1.setVisible(true);
                        break;
                    default:
                        fr2.setVisible(true);
                        break;
                }

                break;
            case 5:
                int dato6 = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero para continuar\n"
                        + "1. Si tienes la Masa[m]" + "\n"
                        + "2. Si tienes la Velocidad Angular [ω]"));
                switch (dato6) {
                    case 1:
                        c1.setVisible(true);
                        break;
                    default:
                        c2.setVisible(true);
                        break;
                }
                break;

        }
        hide();


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Frame_Conversion fr1 = new Frame_Conversion();
        Frame_Conversion2 fr2 = new Frame_Conversion2();

        int dato = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero para ir a la ventana \n"
                + "1. Si quieres convertir la notacion científica a decimal y/o entero" + "\n"
                + "2. Si quieres convertir decimal y/o entero en notación científica"));

        switch (dato) {
            case 1:
                fr1.setVisible(true);
                break;
            case 2:
                fr2.setVisible(true);
                break;
        }
        hide();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Doppler da = new Doppler();
        da.setVisible(true);
        hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reseñas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
